name: puntossmart
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  mailer: ^6.1.2
  orm: ^5.0.4
  path: ^1.9.0
  shelf_cors_headers: ^0.1.5
  uuid: ^4.4.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
