name: puntossmart
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  amazon_cognito_identity_dart_2: ^3.6.5
  crypto: ^3.0.5
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0
  dart_jsonwebtoken: ^2.14.0
  firebase_dart: ^1.2.1
  http: any
  mailer: ^6.1.2
  mercadopago_sdk: ^1.3.0
  orm: ^5.0.4
  path: ^1.9.0
  recase: ^4.1.0
  shelf_cors_headers: ^0.1.5
  uuid: ^4.4.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
